services:
  hashserver:
    build: .
    user: ${HASHSERVER_USER_ID:-0}:${HASHSERVER_GROUP_ID:-0}
    ports:
      - "${HASHSERVER_PORT:?}:${HASHSERVER_PORT:?}"
    environment:
      - HASHSERVER_HOST=${HASHSERVER_HOST:?}
      - HASHSERVER_PORT=${HASHSERVER_PORT:?}
      - HASHSERVER_WRITABLE
    volumes:
      - ${HASHSERVER_DIRECTORY:?}:/buffers