[project]
name = "hashserver"
version = "0.1.0"
description = "Simple FastAPI-based hash server"
license = "MIT"
authors = [{name = "Sjoerd de Vries"}]
requires-python = ">=3.9"
dependencies = [    
    "fastapi",
    "uvicorn[standard]",
    "typing-extensions"
]

[tool.setuptools]
py-modules = ["hashserver", "hash_file_response"]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
hashserver = "hashserver:main"
